name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://github.com/parinya-ao.atom"
          max_post_count: 5
          readme_path: ./README.md
          template: |
            $newline
            * <a href="$url" target="_blank">$title</a> - $date
            $newline
