name: activity

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: ${{ secrets.METRICS_TOKEN}}
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
