name: Parinya Metrics Suite

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 0 * * *'  # ทุกวันเวลาเที่ยงคืน UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: LeetCode Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: parinya-ao
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_limit_recent: 5

      - name: GitHub Follow-up (Indepth)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.followup.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          plugin_followup_archived: no
          config_timezone: Asia/Bangkok

      - name: GitHub Stats Overview
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: Asia/Bangkok

      - name: GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: parinya-ao
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
